// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyynavswxtzhsmwetgtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5eW5hdnN3eHR6aHNtd2V0Z3RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTQ1ODEsImV4cCI6MjA2MzY3MDU4MX0.bm7UieeTN7W9RHw7yDxMP9K8zi3GPu2iAnu_iUeHKdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);